export const APP_KEY =
  "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1MDExOWMwNzhjYmUwMjA3MzVkMGFhMDJiYjdiYTkyNCIsInN1YiI6IjY0MzIxMDRiMWY5OGQxMDFkMzZmNzhhZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.9I_CJK13DctiPb6fUHOte9Kt0akgnrkjrTBgwydlf1A";
export const BASE_URL = "https://api.themoviedb.org/3";
